apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovetest-core

commonLabels:
  app: lovetest-api
  managed-by: argocd

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- secret.yaml
- ingress.yaml

images:
- name: omaticaya/lovetest-core
  newTag: latest
